source 'https://rubygems.org'

gem 'susanoo', '~><%= Susanoo::VERSION %>'
gem 'rake'
gem 'rack'
gem 'rack-rewrite'
gem 'thin'
gem 'uglifier', '>=2.1.1'
gem 'yui-compressor', '>=0.9.6'

gem 'sprockets', '>=2.2.0'
gem 'sass'
gem 'pry'
gem 'rerun'
